#ifndef GPLIB_BT03_VERSION_H
#define GPLIB_BT03_VERSION_H

#define GPLIB_BT03_SVN_VERSION				"SVN:$WCREV$ - $WCRANGE$ "
#define GPLIB_BT03_LIB_BUILD_TIME			"TIME:$WCNOW$"
#endif  // endif GPLIB_BT03_VERSION_H
