#ifndef GPLIB_WFM01A_VERSION_H
#define GPLIB_WFM01A_VERSION_H

#define GPLIB_WFM01A_SVN_VERSION				"SVN:$WCREV$ - $WCRANGE$ "
#define GPLIB_WFM01A_LIB_BUILD_TIME				"TIME:$WCNOW$"
#endif  // endif GPLIB_WFM01A_VERSION_H
