#ifndef GPLIB_ENV_DET_VERSION_H
#define GPLIB_ENV_DET_VERSION_H

#define GPLIB_ENV_DET_SVN_VERSION			"$WCREV$ - $WCRANGE$ "
#define GPLIB_ENV_DET_LIB_BUILD_TIME		"$WCNOW$"
#endif  // endif GPLIB_ENV_DET_VERSION_H
