#ifndef GPLIB_VIDMUX_VERSION_H
#define GPLIB_VIDMUX_VERSION_H

#define GPLIB_VIDMUX_SVN_VERSION			"$WCREV$ - $WCRANGE$ "
#define GPLIB_VIDMUX_LIB_BUILD_TIME			"$WCNOW$"
#endif  // endif GPLIB_VIDMUX_VERSION_H
